// Comprehensive builtin test

println("=== Platform/System ===")
println(platform())
println(arch())
println(hostname())

println("=== Time ===")
println(now())
println(now_ms())
println(year())
println(month())
println(day())
println(hour())
println(minute())
println(second())

println("=== Extended Time ===")
println(weekday())
println(day_of_year())
println(is_leap_year(2024))
println(is_leap_year(2023))

println("=== Math ===")
println(abs(-5))
println(abs(5))
println(min(3, 7))
println(max(3, 7))
println(sqrt(16.0))
println(floor(3.7))
println(ceil(3.2))
println(round(3.5))
println(pow(2.0, 3.0))

println("=== Extended Math ===")
println(sin(0.0))
println(cos(0.0))
println(tan(0.0))
println(trunc(3.9))
println(trunc(-3.9))
println(sign(10))
println(sign(-10))
println(sign(0))
println(clamp(5, 0, 10))
println(clamp(-5, 0, 10))
println(clamp(15, 0, 10))
println(gcd(48, 18))
println(lcm(4, 6))
println(factorial(6))
println(fib(10))

println("=== String ===")
println(len("hello"))
println(upper("hello"))
println(lower("HELLO"))
println(trim("  hi  "))
println(starts_with("hello", "he"))
println(ends_with("hello", "lo"))
println(substring("hello", 1, 3))
println(replace("hello", "l", "x"))
println(index_of("hello", "l"))
println(contains("hello", "ell"))

println("=== Extended String ===")
println(ltrim("  hello"))
println(rtrim("hello  "))
println(char_at("hello", 0))
println(repeat("ab", 4))
println(reverse_str("hello"))
println(is_digit("123"))
println(is_digit("12a"))
println(is_alpha("abc"))
println(is_alpha("ab1"))
println(ord("A"))
println(chr(66))
println(last_index_of("hello", "l"))

println("=== List ===")
let nums = [10, 20, 30, 40, 50]
println(len(nums))
println(first(nums))
println(last(nums))
println(get(nums, 2))

println("=== Type Conversion ===")
println(str(42))
println(int("123"))
println(float("3.14"))
println(bool(1))
println(bool(0))

println("=== All tests done! ===")
